name: Helm Lint

on:
    pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
          chmod 700 get_helm.sh
          ./get_helm.sh

      # Lint the Helm charts
      - name: Lint Helm Charts
        run: |
          helm lint charts/api-service
          helm lint charts/n8n-config

